### ISSUE TITLE
SPIKE : Research on micronaut custom annotation for permissions and roles

### ISSUE THREAD

**Issue by bhatiam12** [oci-labs/check-ins#1146]
Need to find a way to update current services to use new permissions. 

This can be done on check-ins service to see how permissions and roles will impact current services and then open new stories for each service in check-ins.  Please refer to below documentation - 

Micronaut User Guide: https://docs.micronaut.io/latest/guide/

Argument Binding: https://docs.micronaut.io/latest/guide/#customArgumentBinding

Micronaut Security: https://micronaut-projects.github.io/micronaut-security/latest/guide/

SecurityRule: https://micronaut-projects.github.io/micronaut-security/latest/guide/#securityRule

Authentication Providers (mentioned at the end of the call): https://micronaut-projects.github.io/micronaut-security/latest/guide/#authenticationProviders

AC: Document and submit a pr to use new permissions and roles.

**Comment by HootDunk** [comment]
I've been looking into this a bit and somehow missed this article but it looks very promising -> https://blog.wick.technology/micronaut-security-rule/

**Comment by HootDunk** [comment]
Working demo of a custom security annotation -> https://github.com/HootDunk/custom-security-demo
