### ISSUE TITLE
Cannot add myself to Guild (M)

### ISSUE THREAD

**Issue by brianjohnson5972** [oci-labs/check-ins#1272]
For my checkin page, I tried to add myself to he Blockchain guild, but it never displays what I select.  Since I can only see my edit page and not the page everyone else sees, I don't know if it is an issue with it not actually setting the value or just not displaying the selected value after it is selected.
My guild page looks like:
![this](https://user-images.githubusercontent.com/10270043/126657205-46db3d93-4be1-4726-87a8-f707f43bceb3.JPG)

**Comment by HootDunk** [comment]
Similarly, when I try to add myself to a guild I get an error that I'm not authorized to perform the operation but when I go to the guilds page I can see that I was added to the guild.
![image](https://user-images.githubusercontent.com/58009556/126661175-4ff6a951-6c1b-4e29-bcc9-49abe292072c.png)

It seems like there is a bug that needs fixing, but I also think some visual cues as to what guilds one is a part of underneath the "Join a guild" would be helpful.

**Comment by brianjohnson5972** [comment]
I went and checked and originally it was added.  Then I told the fellow Blockchain team members to add themselves to the guild, and then my name was no longer showing up as part of the guild
![image](https://user-images.githubusercontent.com/10270043/126674056-ea52bc69-f074-43b0-914f-5ad7bf0d9e73.png)

**Comment by brianjohnson5972** [comment]
I tried again and, after giving me the error, I went to the guilds page and I showed up, then disappeared after I refreshed the page.

**Comment by brianjohnson5972** [comment]
@jahanner Do you know when the website will be updated, so I know when I can add myself?

**Comment by jahanner** [comment]
@brianjohnson5972 I don't know an exact date but I'll ask Michael once he gets back from vacation and let you know.
