### ISSUE TITLE
Update README to reflect updated project purpose, name, usage, etc.

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#13]

**Comment by mkimberlin** [comment]
See: https://github.com/objectcomputing/innovation-labs

**Comment by Bagurp** [comment]
copy https://github.com/objectcomputing/innovation-labs/blob/master/CONTRIBUTING.md to this repo as part of this story.

**Comment by steinkampr** [comment]
Closed 6/23
