### ISSUE TITLE
BE > Create migration for creating checkin_notes table (S)

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#145]
A new flyway migration should be added to create the table - checkin_notes

Definition of Done:

- [ ] new flyway migration has been created to create the table checkin_notes
- [ ] a schema has been generated and shared

Table should include the following columns:

uuid (varchar required)
checkinId (varchar references checkin table required)
createdById (varchar references member_profile table required)
private (boolean required)
description (varchar)

**Comment by bhatiam12** [comment]
@mkimberlin `private (boolean required)` means something like if notes are private or not ?
