### ISSUE TITLE
BE > Refactor all services to be served under /services (M)

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#146]
In order to allow the SPA to have dynamic routing, we need to move all of the services under a predictable URL.

- [ ] alter every existing service to be served up under a root URL
- [ ] alter controller tests as needed to reflect the URL change

**Comment by chrismckiernan** [comment]
This may be OBE since we decided the initial approach wasn't feasible. We already are in the process of updating the endpoints.
