### ISSUE TITLE
FE > Alter the way sign in works (M)

### ISSUE THREAD

**Issue by sharmag04** [oci-labs/check-ins#165]
Definition of Done

- [x] initiate OAuth process on launch application  
- [x] Remove sign in menu item from the avatar
- [x] create a /user endpoint that returns email and image_url from google Oauth

**Comment by Bagurp** [comment]
- created the endpoint at /services/member-profile/current
- when an existing user enters the application, we'll find memberProfile using email address and return it.
- when a new user enters the application, we'll create a record and return it. Name, email address and image_url are fetched from Auth token.
