### ISSUE TITLE
Create RESTful service for managing a team member profile

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#17]
All CRUD actions needed.

**Comment by mkimberlin** [comment]
PDL should probably be a field on the team member profile...also need a search method

**Comment by mkimberlin** [comment]
Base URL: /team-member

Entity should contain:
  UUID
  Name
  Role
  PDL - UUID of PDL Team Member
  Location
  Company Email
  Insperity ID
  Profile Image URL
  Start Date
  Prior Tenure (Months)
  Bio Text

Create
Read
  Find by:
    Name
    Role
    PDL
Update
Delete

**Comment by steinkampr** [comment]
Closed in 6/23 DSU
