### ISSUE TITLE
FE > Create action items component (L)

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#197]
Create a component that allows for the management of a Check-In's action items.

Definition of Done

- [ ] Component is created similar to this mockup but with (-) icon on the right for deletion and vertical ellipsis on the left for reordering on each action item:
<img width="700" alt="Screen Shot 2020-08-12 at 12 05 14 PM" src="https://user-images.githubusercontent.com/100510/90065470-f2db4580-dcb1-11ea-88cb-b336a95ac81a.png">

- [ ] Component accepts a check-in id and retrieves the action items for the check-in for display
- [ ] Component displays each action item once loaded 
- [ ] Component appears similar to this while loading:
![Action Items - Loading](https://user-images.githubusercontent.com/100510/90066867-ee179100-dcb3-11ea-976a-fd832d6e2759.png)

- [ ] Component updates action items on change (via REST service)
- [ ] Component allows for deletion of action items (via REST service)
- [ ] Component allows for the addition of action items (via REST service)
- [ ] Component allows for the reordering of action items (via REST service)
- [ ] Snapshot test(s) have been created for the component
- [ ] Applicable unit tests have been created for the component
- [ ] Code has been submitted for PR and accepted

**Comment by meyerinj** [comment]
Couple Qs:

Is this component intended to go on the side bar of the check-ins page, similar to the guides component Zack and I worked on? Or its own page?

There is a requirement to be able to reorder the list. What should they be ordered by by default?

**Comment by meyerinj** [comment]
Additional question: It's not clear what data is supposed to be displayed for each record. There's a description field obvi, but there are also UUIDs for what I assume are a CheckIn and TeamMember object. What data from them is needed?

**Comment by mkimberlin** [comment]
> Is this component intended to go on the side bar of the check-ins page, similar to the guides component Zack and I worked on? Or its own page?

It is a section in the main content of the check-ins page.

> There is a requirement to be able to reorder the list. What should they be ordered by by default? 

Reorder is part of the DoD above. Natural ordering (by creation time).

**Comment by meyerinj** [comment]
> Reorder is part of the DoD above. Natural ordering (by creation time).

The requirement also says the order should be persisted via a REST service. Obviously we can't change the creation time when we reorder the records.

**Comment by mkimberlin** [comment]
Only the initial ordering should be natural...that's really a matter of just putting new ones at the bottom. We will need to persist an order. Sorry...didn't mean to suggest that we would control it by creation time.

**Comment by meyerinj** [comment]
@sharmag04 Reopening to resolve the unmet criteria.
