### ISSUE TITLE
BE > Alter document upload service to handle associations with check-in (M)

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#209]
The `/upload` service needs to be altered to handle document associations with a check-in. It might be worth renaming to something like `/file` as well.

Definition of Done:
- [ ] an endpoint is created for `find by` (check-in id) and/or `find all`
  - [ ] find all should only be allowed by an ADMIN
  - [ ] find by id should only be allowed by:
    - [ ] ADMIN
    - [ ] the current PDL for the user whose check-in it is
    - [ ] PDL for that check-in 
- [ ] an endpoint is created for retrieving the document information (by id)
- [ ] an endpoint is created for retrieving the document contents (maybe `/upload/{id}/download` 😂)
- [ ] an endpoint is created for `create`
  - [ ] endpoint creates a folder within the configured root location named `lastname, firstname - YYYY.MM.DD` if it does not already exist
    - [ ] if it already exists, it that folder is used.
  - [ ] endpoint uploads the file to the created or found named directory
  - [ ] endpoint creates an association to the uploaded document id via the `checkin_document` table
- [ ] an endpoint is created for `delete`
  - [ ] the delete endpoint removes the uploaded document id entry for the document
  - [ ] the delete endpoint removes the document from Google Drive
- [ ] unit tests are created for each endpoint
- [ ] end-to-end test container tests are created for each endpoint
- [ ] code is submitted as a pull request
- [ ] swagger configuration
  - [ ] add schema definition to the entity
- [ ] controller logic and service logic are split into different layers
- [ ] define appropriate DTOs
- [ ] implement appropriate error handlers
- [ ] make use of the headers for location on create method

**Comment by Bagurp** [comment]
- [ ] update GoogleAuthenticator and remove deprecated functions
- [ ] set up property 'google credentials' to be passed in as env variable
- [ ] update github project workflow to add the property 'google credentials'
