### ISSUE TITLE
BE> Convert Guild service tests to use test containers (M)

### ISSUE THREAD

**Issue by sharmag04** [oci-labs/check-ins#257]
Definition of Done

- [ ] run coverage test on newly created controller test 
- [ ] ensure code coverage of 80% for involved classes
- [ ] Controller is annotated with `@Secured(IS_AUTHENTICATED)`
- [ ] Unit tests are updated to use `.basicAuth()` call

**Comment by bhatiam12** [comment]
@sharmag04 isn't this same as issue #242 ?

**Comment by sharmag04** [comment]
@bhatiam12 Yes it looks like a duplication. Closing this one.
