### ISSUE TITLE
Set up PostgreSQL

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#27]
As a cloud architect I would like to have the ability to script infrastructure as code. The CloudOps team is getting behind using Terraform in order to make the process of deployment to higher level environments seamless and straight forward.

- [x] Look at PulseSurvey docker-compose.xml. 
- [x] Plan how the database is going to fit into the over all architecture. **One DB for stage, one DB for prod**
- [x] Analyze how to structure Terraform to apply the scripts to make the database. **script written**
- [x] Develop the script to create the db and return the credentials **able to run in cloud shell**
- [x] Implement the scripts into the infrastructure repo. **scripts have been implemented**

**Comment by sharmag04** [comment]
AC 1: Set up in the test environment
AC 2: Set up in the prod environment

**Comment by jorwalk** [comment]
I have created a terraform script that enables us to create a database through code. 

https://www.terraform.io/docs/providers/google/r/sql_database_instance.html

**Comment by jorwalk** [comment]
> Issue status

## Infrastructure Repository
The Terraform code has been checked into the Gitlab CloudOps [repository](https://gitlab.cloudops.objectcomputing.com/skills/infrastructure). The code is ran in CloudShell, the commands are init, plan, apply.  Changes are committed from CloudShell directly to Gitlab.

The database layouts have been included in the architecture overview image.



### AC 1: Set up in the test/dev environment
This has been completed for the development environment

### AC 2: Set up in the prod environment
This is not yet necessary and will need to be moved into another issue.
