### ISSUE TITLE
Setup automated build

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#28]
Just build and run tests

**Comment by sharmag04** [comment]
AC 1: Feature work flow exist in github actions
AC 2: Master and Develop flow exist in github actions

**Comment by bhatiam12** [comment]
@mkimberlin  are we planning to include SonarCloud analysis as well(Its free for public projects) ?

**Comment by mkimberlin** [comment]
> @mkimberlin  are we planning to include SonarCloud analysis as well(Its free for public projects) ? 

I'm up for that if the team is. Make an issue for it.
