### ISSUE TITLE
Set up continuous deployment in the test environment

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#29]
As a cloud architect I would like to be able to deploy the develop branch into a separate environment than production.
- [x] Debug the build failing to start
- [x] Plan how the test environment will be configured and place inside GCP
- [x] Analyze what is going to need to be completed in order for the environment to be accessed
- [x] Develop scripts and necessary pipeline configuration changes
- [x] Implement and run the scripts and tests to ensure they are working as expected. 
- [x] Send the necessary secrets that have the iam json role to `mkimberlin` to add to Github Action Secrets setttings.

**Comment by jorwalk** [comment]
- https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/gce/.github/workflows/gce.yaml
- https://github.com/GoogleCloudPlatform/github-actions/tree/master/example-workflows/gae

**Comment by jorwalk** [comment]
**Links that I found help**
- https://github.com/marketplace/actions/google-app-engine-gae-deploy
- https://github.com/marketplace/actions/publish-app-to-google-app-engine
- https://baskus.wordpress.com/2019/09/29/how-to-deploy-to-app-engine-using-github-actions/

**Comment by jorwalk** [comment]
> ERROR: An app.yaml (or appengine-web.xml) file is required to deploy this directory as an App Engine application. Create an app.yaml file using the directions at https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml (App Engine Flexible Environment) or https://cloud.google.com/appengine/docs/standard/python/config/appref (App Engine Standard Environment) under the tab for your language.
ERROR: (gcloud.app.deploy) [/home/runner/work/my-first-micronaut/my-first-micronaut] could not be identified as a valid source directory or file.

More work will need to be done in order to run on AppEngine: https://guides.micronaut.io/micronaut-gradle-google-cloud/guide/index.html

**Comment by jorwalk** [comment]
@mkimberlin @bhatiam12 

The build step for `Deploy image to Cloud Run` is failing due to this exception `org.postgresql.util.PSQLException: Connection to localhost:5432 refused`

As seen here:
https://github.com/oci-labs/check-ins/runs/845713071?check_suite_focus=true

This story is now blocked until this pull request is merged into develop:
https://github.com/oci-labs/check-ins/pull/74

**Comment by jorwalk** [comment]
The URL for this is : https://checkins-develop-tuvcfzotpq-uc.a.run.app/
