### ISSUE TITLE
BE> Split flyway scripts by environment

### ISSUE THREAD

**Issue by meyerinj** [oci-labs/check-ins#312]
See #297 for info on how this works. In addition to what it outlined there the existing scripts should be renamed from V1, V2, etc... date versions as outlined [here](https://flywaydb.org/documentation/migrations#versioned-migrations).

Acceptance Criteria:

- [ ] A folder (e.g. db/common) for scripts that must run in all environments
- [ ] A [repeatable script](https://flywaydb.org/documentation/migrations#repeatable-migrations) in another folder (e.g. db/local) which is only run when MICRONAUT_ENVIRONMENTS=local that creates two member_profile records (one as the other's PDL)

**Comment by mkimberlin** [comment]
I think we want it to run both local and in our dev env, no? Ultimately, I'd like those repeatable scripts to clear out and set up a basic set of data that would allow us to easily smoke test and/or demo. Maybe that's misguided? I'd be interested to hear from the team on this.

**Comment by meyerinj** [comment]
I wasn't sure how much starter data we'd want so I stuck with just barely enough to demonstrate the repeatable script.

I would argue that for demos it would be worth having a separate script in db/demo that would set us up with a full data set to demo from whereas db/common would just be a bare minimum for developing with.

**Comment by meyerinj** [comment]
The flyway scripts are currently split into "common" and "dev". This is done, right? @mkimberlin

**Comment by mkimberlin** [comment]
Yeah, pretty sure we're good @meyerinj
