### ISSUE TITLE
Understanding the cloud architecture

### ISSUE THREAD

**Issue by sharmag04** [oci-labs/check-ins#37]
As a cloud architect it is important to understand the high level infrastructure as well as the low level REST endpoints.

- [x] a diagram has been created that show how the infrastructure is put in place.
- [x] documentation about the endpoints has been created with markdown
- [x] the diagram shows how Github Actions will integrate with AppEngine

**Comment by mkimberlin** [comment]
How are we splitting data stores? DB per service? One DB? Some Hybrid?
Continue to use App Engine?

**Comment by jorwalk** [comment]
<img width="418" alt="Screen Shot 2020-06-23 at 11 08 04 AM" src="https://user-images.githubusercontent.com/119564/85430172-65973280-b545-11ea-82a2-a97d94497573.png">

**Comment by jorwalk** [comment]
@Maroju100 - here is a start to the diagram for the architecture.
The file can be edited with this url: https://drive.google.com/file/d/1TBQbfrS8Ylv83_i1JVKeVpEQF0fM_o2V/view?usp=sharing

**Comment by jorwalk** [comment]
https://github.com/oci-labs/check-ins/wiki

**Comment by jorwalk** [comment]
1. How are we splitting data stores? **No**
1. DB per service? **No**
1. One DB? **Yes**
1. Some Hybrid? **No**
1. Continue to use App Engine? **Yes**
