### ISSUE TITLE
GCP > Set up continuous deployment in the prod environment (M)

### ISSUE THREAD

**Issue by sharmag04** [oci-labs/check-ins#38]
As a cloud developer I would like to have the ability to manually / automatically promote the code base to a production environment.

- [x] Plan how the Github master branch will be first merged into, and subsequently trigger Cloud build to build/test/deploy the changes
- [x] Analyze the code to build and deploy the infrastructure in GCP, what changes need to be included to support two different environments
- [x] Run `gcloud` command to create a container optimized compute engine image
- [x] Update the master branch action yaml to deploy to GCE.
- [x] Create a new database for production
- [x] Coordinate with Chuck to assign environment specific DNS: `https://dev.checkins.objectcomputing.com`
or
`https://checkins-dev.objectcomputing.com`

**Comment by jorwalk** [comment]
This is blocked:
```
Until the upload issue is fixed, I don't want to merge to the main branch. Beyond that, I'd like to be able to merge at the end of every sprint, but we need adequate automated testing in place before we talk about merging at a cadence. We need a demo and a discussion until we get testing established, IMHO.
```

**Comment by jorwalk** [comment]
A database has been created and the credentials have been shared with the project manager in order to add them to the github secrets

**Comment by jorwalk** [comment]
```
PROD_DB_NAME
PROD_RUN_PROJECT
PROD_DB_CONNECTION_NAME
PROD_DB_PASSWORD
```

**Comment by jorwalk** [comment]
This is setup to use CloudRun
