### ISSUE TITLE
Investigate secret management

### ISSUE THREAD

**Issue by sharmag04** [oci-labs/check-ins#39]
As a cloud engineer, I want the ability to be able to store cloud credentials with encryption at rest, while providing the capability of retrieving those credentials during deployment pipeline.

- [x] plan how secret manager will be leveraged.
```
secrets will need to be stored for the database and gcp service account
```
- [x] analyze how the secret key value sets will be stored and retrieved
```
secrets will be set in the GitHub Settings > Action 
```
- [x] implement the initialization, creation, and retrieval of a secret
```
this information has been documented in the link shared in the comments
```
- [x] add the design to the architecture documentation knowledge base

**Comment by jorwalk** [comment]
@mkimberlin - after reviewing how the build is and can be configured with Actions, I see there is a secrets within Actions, as denoted by `${{ secrets.GITHUB_TOKEN }}`

We can use this: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

I can create a service account that Actions uses to deploy into AppEngine and store the credentials to be used in a `workflow`
