### ISSUE TITLE
Configure application to use Postgresql on GCP

### ISSUE THREAD

**Issue by sharmag04** [oci-labs/check-ins#40]
As an application developer, I want the ability to connect to a database and have the configuration credentials available as environment variables.

**Done**
- [x] research has been completed to see how to best differentiate environment from a Github Actions workflow CI/CD pipeline.
- [x] the application is able to connect to a cloud sql deployment

**Comment by jorwalk** [comment]
- [ ]  ability to retrieve the credentials from secret manager is setup in pipeline
- [ ] what is the best practice of injecting environment variables into a micronaut application

**Comment by bhatiam12** [comment]
@mkimberlin I am closing this as this has been completed and tested.
