### ISSUE TITLE
BE> Create service for tagging entities (M)

### ISSUE THREAD

**Issue by sharmag04** [oci-labs/check-ins#407]
- [x] Add a UUID for the tag itself
- [x] Add a name for the tag
- [x] Add a type for the tag
- [x] Update tests as needed

**Comment by meyerinj** [comment]
Are there any acceptance criteria for this? From the name I'm gathering we want there to be tags which can have a many-to-many relationship with skills? Is that right?

**Comment by mkimberlin** [comment]
Correct.
