### ISSUE TITLE
BUG > Notes are not updated (S)

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#566]
When altering either Notes or Private Notes, the service is not called to store the changes

Current Behavior: No update service call is made for the note

Expected Behavior: The changes are saved to the note

**Comment by bhatiam12** [comment]
@mkimberlin I am trying tp update the note and seeing 200. is there a particular scenario where this doesn't work ? I am logged in as ADMIN on my local. below is the payload-
```{id: "c3211038-9d6b-4799-91c1-c33dd6566d6f", checkinid: "8aa38f8c-2169-41b1-8548-1c2472fab7ff",…}
checkinid: "8aa38f8c-2169-41b1-8548-1c2472fab7ff"
createdbyid: "b2d35288-7f1e-4549-aa2b-68396b162490"
description: "sssereccxcx"
id: "c3211038-9d6b-4799-91c1-c33dd6566d6f"```

**Comment by mkimberlin** [comment]
@bhatiam12 the issue isn't the service, it's the UI. It's not calling the service.

**Comment by bhatiam12** [comment]
> @bhatiam12 the issue isn't the service, it's the UI. It's not calling the service.

@mkimberlin right but when I try from my local it is calling the service just fine. maybe I am again having the issue where I don't see new front end changes on my local machine.
