### ISSUE TITLE
CHORE > Data Security Review (S)

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#579]
We need to review (with support from the security guild, perhaps) the data stored in the application to identify PII and other sensitive data that needs to be encrypted for storage:

DoD:
- [x] The entire database schema has been reviewed for PII and other sensitive data
- [x] All identified data is documented in an issue to perform the necessary encryption

Necessary fields to encrypt include:

### Table: member_profile
- [x] name
- [x] title
- [x] location
- [x] workemail
- [x] biotext

### Table: team
- [x] name
- [x] description

### Table: action_items
- [x] description

### Table: agenda_items
- [x] description

### Table: checkin_notes
- [x] description

### Table: private_notes
- [x] description

### Table: pulse_response
- [x] internalfeelings
- [x] externalfeelings

**Comment by bhatiam12** [comment]
![image](https://user-images.githubusercontent.com/66330160/104525386-a9c35080-55c5-11eb-96e9-f86625492c79.png)
