### ISSUE TITLE
SPIKE> Develop approach to encrypt database fields (M)

### ISSUE THREAD

**Issue by sharmag04** [oci-labs/check-ins#631]
DoD:

- [ ] configuration of necessary keys/ passwords is done through GitHub secrets
- [ ] encryption/decryption can be done on individual fields
- [ ] approach supports extension to use different keys for slices of the database in future
- [ ] ideally approach is supported by Micronaut data

**Comment by bhatiam12** [comment]
@mkimberlin please can you paste the link that you found related to encryption here ?

**Comment by sharmag04** [comment]
@bhatiam12 here you go
https://www.enterprisedb.com/blog/how-to-secure-postgresql-security-hardening-best-practices-checklist-tips-encryption-authentication-vulnerabilities?utm_source=google&utm_medium=cpc&utm_campaign=Q42020_NA&gclid=CjwKCAiAiML-BRAAEiwAuWVggrjfi1ay1lpJIcbZR6Uu8i8q7Y_qugmXqtaD9k2TDHWwsTSUNEh9gxoCJP4QAvD_BwE

**Comment by mkimberlin** [comment]
Thanks, @sharmag04 !

**Comment by mkimberlin** [comment]
This is completed in the encrypt_postgres branch. However, it will be merged in under #697
