### ISSUE TITLE
FE > Edit team member should allow for editing of member name

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#653]
- [ ] Add the team member name as a field to the edit dialog (currently available in add)
- [ ] Adjust call to persist, if necessary
- [ ] Alter any snapshot and unit tests

**Comment by dimky01** [comment]
I am very interested in this project. Could I be assigned to this issue?

**Comment by mkimberlin** [comment]
@dimky01 Hi! Welcome. I'm sorry that I didn't see your message yesterday. If you would like to take a shot at this one, that would be fine.

**Comment by mkimberlin** [comment]
@dimky01 It seems that this one is already going to be handled by some work that's in progress. Can I point you to a different story that might be a good first one to take on?  Are you interested in primarily front end stories (React.js) or backend (Java with Micronaut)?

**Comment by dimky01** [comment]
Hi @mkimberlin, Apologies for the late response. I wouldn't mind if you point me to another story since this one is not available. I will be much interested in backend stories
