### ISSUE TITLE
Team page does not look good on small screens and mobile

### ISSUE THREAD

**Issue by hwilliams314** [oci-labs/check-ins#726]
The teams page looks funny on screen sizes smaller than 828 px width and on most of the mobile formats. 

<img width="300" alt="Screen Shot 2021-02-25 at 12 33 45 PM" src="https://user-images.githubusercontent.com/48927697/109200373-24a38d80-7766-11eb-9fb4-a0e2debfcb73.png">
<img width="300" alt="Screen Shot 2021-02-25 at 12 34 14 PM" src="https://user-images.githubusercontent.com/48927697/109200388-29684180-7766-11eb-9b1e-fa4013c00475.png">
<img width="300" alt="Screen Shot 2021-02-25 at 12 35 21 PM" src="https://user-images.githubusercontent.com/48927697/109200399-2bca9b80-7766-11eb-91cb-2d17f165d3cc.png">
<img width="300" alt="Screen Shot 2021-02-25 at 12 35 45 PM" src="https://user-images.githubusercontent.com/48927697/109200402-2e2cf580-7766-11eb-87c6-cf06da551260.png">
<img width="300" alt="Screen Shot 2021-02-25 at 12 34 35 PM" src="https://user-images.githubusercontent.com/48927697/109200411-2ff6b900-7766-11eb-91c9-0c570259e1f1.png">

**Comment by mkimberlin** [comment]
I'm not experiencing this...still an issue @hwilliams314 ?

**Comment by Maroju100** [comment]
Seems to be fixed, I don't see the issue anymore. Closing the issue.
