### ISSUE TITLE
Convert all REST service URLs to consistent naming

### ISSUE THREAD

**Issue by mkimberlin** [oci-labs/check-ins#794]
This is a big beast, and I'm going to beg @sharmag04 to help me break it down into stories for the team, likely by service, now that I've written this all out.

Each of the base URLs for the REST services should be converted to plural (which very few, singular by nature, exceptions)
i.e. `/services/action-item` to `/services/action-items`

## Definition of Done
- [ ] Each singular service URL has been changed to plural
    - [ ] `/services/action-item`
    - [ ] `/services/agenda-item`
    - [ ] `/services/checkin-note`
    - [ ] `/services/checkin-document`
    - [ ] `/services/check-in`
    - [ ] `/services/file`
    - [ ] `/services/guild`
    - [ ] `/services/member-skill`
    - [ ] `/services/member-profile`
    - [ ] `/services/member-profile/current` -> `/services/member-profiles/current` (note that current stays singular)
    - [ ] `/services/member-profile/member-photo`
    - [ ] `/services/private-note`
    - [ ] `/services/pulse-response`
    - [ ] `/services/role`
    - [ ] `/services/skill`
    - [ ] `/services/tag`
    - [ ] `/services/entity_tag` -> `/services/entity-tags`
    - [ ] `/services/team`
    - [ ] `/services/team-member` -> `/services/team-members`
- [ ] The web-ui API urls have been altered for each changed for each of the above services
- [ ] Tests have been altered to reflect the changes in each service

**Comment by sharmag04** [comment]
Have created individual stories for each REST service so closing this one.
