### ISSUE TITLE
Member lists are not alphabetically ordered (M)

### ISSUE THREAD

**Issue by warnerj-oci** [oci-labs/check-ins#857]
Definition of Done

The member lists under:
- [ ] Teams - Team Leads and Team Members drop down need to be alphabetized by first name
- [ ] Directory - In Edit Member, the Supervisors list need to be alphabetized by first name

**Comment by sharmag04** [comment]
Creating a new issue for this so closing this one

**Comment by sharmag04** [comment]
Reopening and adding additional DoD to the same issue.

**Comment by jahanner** [comment]
@sharmag04 @mkimberlin Should we also alphabetize the PDL list right above the Supervisor list?

**Comment by mkimberlin** [comment]
@jahanner yes, probably
