### ISSUE TITLE
Set up feedback CI/CD

### ISSUE THREAD

**Issue by pieperm** [oci-labs/check-ins#965]
- [x] Grant access to interns to GCP project
- [x] Create feedback branch
- [x] Enable natural language API
- [x] Set up development environment
- [x] Enable Google Chat API

**Comment by mkimberlin** [comment]
I've reached out to our cloud team to try to get some support on the environment. The branch, your access, and the APIs have been set up, however. @sagetheherb @pieperm @Approve212 @smithj11 @JEdwardBrown @moshirim
