### ISSUE TITLE
FE: Creating due date & sent on selection component. (S)

### ISSUE THREAD

**Issue by moshirim** [oci-labs/check-ins#976]
## DoD:

- [x] Integrate the date input field using material UI
- [x] Integrate date input into state tracking (Include it in the local state)
- [x] Sent on should be defaulted to the current day
- [x] Due date should be defaulted to nothing. The place holder should say "No due date."

**Comment by smithj11** [comment]
Merged in some time ago into feedback. Not sure why issue still open
